title: Shahriar Kabir Khan
logo: /assets/img/Kabir_logo.png
description: >
  Welcome to my portfolio.

  <p align="center">
      <a href="assets/pdf/CV - Shahriar Kabir Khan.pdf">Resume</a> |
      <a href="https://www.linkedin.com/in/kabiruh19/">LinkedIn</a> |
      <a href="https://stackoverflow.com/users/9453613/shahriar-kabir-khan">Stack Overflow</a>
  </p>

  <p align="justify">
      <br><br>
      Hello, I am Shahriar Kabir Khan (known as Kabir). Recently, I completed my Digital, Data and Technology Graduate scheme at NHS England as a Data Engineer.
      <br><br>
      Previously, I worked as a Data Curator at Health Data Research UK, where I also completed my one-year industrial experience as a Data Engineer Intern as part of my MSc degree. My work focuses on handling large amounts of health data, including creating data pipelines on Microsoft Azure, debugging and testing, data wrangling, visualizing, and deploying.
      <br><br>
      I hold an MSc in Artificial Intelligence from Queen Mary University of London and completed my BSc in Software Engineering.
      <br><br>
  </p>

show_downloads: true
google_analytics: "" # Add your Google Analytics tracking ID here if applicable
theme: jekyll-theme-minimal
